name: Deploy to GitHub Pages

on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    env:
      NEXT_PUBLIC_BASE_PATH: ""

    steps:
      - name: Checkout project-portal
        uses: actions/checkout@v3
        with:
          repository: SUSE/project-portal
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: 18
      - name: Install packages
        run: npm ci
      - name: Build project
        run: npm run build
      - name: Export static files
        run: npm run export
      - name: Add .nojekyll file
        run: touch ./out/.nojekyll
      - name: Checkout main branch
        uses: actions/checkout@v3
        with:
          path: static
      - name: Copy static files
        run: cp -pr static/suse-open-source-policy.html out/
      - name: Bundle for saving
        run: tar --directory out/ -hcf artifact.tar .
      - name: Saving bundle
        uses: actions/upload-artifact@v3
        with:
          name: github-pages
          path: ./artifact.tar
  deploy:
    needs: build
    runs-on: ubuntu-latest
    permissions:
      pages: write
      id-token: write
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - id: deployment
        uses: actions/deploy-pages@v1
